/* Taǧwīd-Quiz „Regel erkennen“: eine Stelle aus dem Qurʾān, ein Teil ist markiert – welche Regel gilt dort?
   Jede Aufgabe: { s: Stelle, m: markierte Wörter (genau so wie in s), r: Regel (Name aus RULES),
                   f: worauf man achten soll (optional), v: Sūra:Vers, e: Erklärung }
   Die falschen Antworten nimmt tajwid.js aus der ersten Gruppe (GROUPS), die die Regel enthält – damit man wirklich unterscheiden muss.
   Lesart Ḥafṣ ʿan ʿĀṣim. */
window.TAJWID_REGELN = {
  GROUPS: [
    ["Iẓhār ḥalqī", "Idġām mit Ġunna", "Idġām ohne Ġunna", "Iqlāb", "Iḫfāʾ", "Iẓhār muṭlaq"],
    ["Iḫfāʾ šafawī", "Iẓhār šafawī", "Idġām šafawī (Mīm in Mīm)", "Ġunna (Nūn/Mīm mit Šadda)", "Iqlāb"],
    ["Madd ṭabīʿī", "Madd muttaṣil", "Madd munfaṣil", "Madd lāzim kalimī", "Madd lāzim ḥarfī", "Madd ʿāriḍ li-s-sukūn", "Madd al-līn", "Madd al-badal", "Madd aṣ-ṣila ṣuġrā", "Madd aṣ-ṣila kubrā", "Madd al-ʿiwaḍ"],
    ["Lām šamsiyya", "Lām qamariyya", "Lām in „Allah“ dick", "Lām in „Allah“ dünn"],
    ["Rāʾ dick", "Rāʾ dünn", "Lām in „Allah“ dick", "Lām in „Allah“ dünn"],
    ["Idġām miṯlayn", "Idġām mutaǧānisayn", "Idġām mutaqāribayn", "Idġām ohne Ġunna", "Sakt"],
    ["Qalqala ṣuġrā", "Qalqala kubrā", "Lām qamariyya", "Iẓhār ḥalqī", "Iḫfāʾ"]
  ],
  ITEMS: [
    /* Nūn sākina und Tanwīn */
    { s: "إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ", m: "آمَنُوا", r: "Madd al-badal", f: "das ā am Anfang", v: "98:7", e: "Hamza vor dem Dehnungsbuchstaben im selben Wort → badal, 2 Ḥarakāt." },
    { s: "مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ", m: "مَنْ آمَنَ", r: "Iẓhār ḥalqī", f: "das Nūn von مَنْ", v: "2:62", e: "Nūn sākin vor Hamza (Kehllaut) → deutlich." },
    { s: "وَلَهُمْ عَذَابٌ أَلِيمٌ", m: "عَذَابٌ أَلِيمٌ", r: "Iẓhār ḥalqī", f: "das Tanwīn", v: "2:10", e: "Tanwīn vor Hamza → deutlich." },
    { s: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ", m: "أَنْعَمْتَ", r: "Iẓhār ḥalqī", f: "das Nūn", v: "1:7", e: "Nūn sākin vor ʿAyn → deutlich." },
    { s: "فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", m: "ذَرَّةٍ خَيْرًا", r: "Iẓhār ḥalqī", f: "das Tanwīn", v: "99:7", e: "Tanwīn vor Ḫāʾ (Kehllaut) → deutlich." },
    { s: "فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", m: "خَيْرًا يَرَهُ", r: "Idġām mit Ġunna", f: "das Tanwīn", v: "99:7", e: "Tanwīn vor Yāʾ (يُومِنُ) über zwei Wörter → Idġām mit Ġunna." },
    { s: "وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ", m: "وَمَنْ يَعْمَلْ", r: "Idġām mit Ġunna", f: "das Nūn", v: "99:8", e: "Nūn sākin vor Yāʾ → may-yaʿmal." },
    { s: "وَخَلَقَ الْجَانَّ مِنْ مَارِجٍ مِنْ نَارٍ", m: "مِنْ نَارٍ", r: "Idġām mit Ġunna", f: "das Nūn von مِنْ", v: "55:15", e: "Nūn sākin vor Nūn → Idġām mit Ġunna." },
    { s: "أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ", m: "مِنْ رَبِّهِمْ", r: "Idġām ohne Ġunna", f: "das Nūn", v: "2:5", e: "Nūn sākin vor Rāʾ → vollständig, ohne Ġunna." },
    { s: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِلْمُتَّقِينَ", m: "هُدًى لِلْمُتَّقِينَ", r: "Idġām ohne Ġunna", f: "das Tanwīn", v: "2:2", e: "Tanwīn vor Lām → ohne Ġunna." },
    { s: "إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ", m: "غَفُورٌ رَحِيمٌ", r: "Idġām ohne Ġunna", f: "das Tanwīn", v: "2:173", e: "Tanwīn vor Rāʾ → ġafūrur-raḥīm." },
    { s: "ثُمَّ عَفَوْنَا عَنْكُمْ مِنْ بَعْدِ ذَٰلِكَ", m: "مِنْ بَعْدِ", r: "Iqlāb", f: "das Nūn", v: "2:52", e: "Nūn sākin vor Bāʾ → Mīm mit Ġunna." },
    { s: "إِنَّ اللَّهَ سَمِيعٌ بَصِيرٌ", m: "سَمِيعٌ بَصِيرٌ", r: "Iqlāb", f: "das Tanwīn", v: "22:75", e: "Tanwīn vor Bāʾ → samīʿum-baṣīr." },
    { s: "كَلَّا لَيُنْبَذَنَّ فِي الْحُطَمَةِ", m: "لَيُنْبَذَنَّ", r: "Iqlāb", f: "das erste Nūn", v: "104:4", e: "Nūn sākin vor Bāʾ im selben Wort → Iqlāb." },
    { s: "وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ", m: "يُنْفِقُونَ", r: "Iḫfāʾ", f: "das Nūn", v: "2:3", e: "Nūn sākin vor Fāʾ → verborgen, mit Ġunna." },
    { s: "الَّذِينَ هُمْ عَنْ صَلَاتِهِمْ سَاهُونَ", m: "عَنْ صَلَاتِهِمْ", r: "Iḫfāʾ", f: "das Nūn", v: "107:5", e: "Nūn sākin vor Ṣād → Iḫfāʾ." },
    { s: "جَنَّاتٍ تَجْرِي مِنْ تَحْتِهَا الْأَنْهَارُ", m: "جَنَّاتٍ تَجْرِي", r: "Iḫfāʾ", f: "das Tanwīn", v: "2:25", e: "Tanwīn vor Tāʾ → Iḫfāʾ." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "وَالْفَتْحُ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "110:1", e: "Fāʾ ist ein Mondbuchstabe → das Lām wird gesprochen." },
    { s: "وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ", m: "الدُّنْيَا", r: "Iẓhār muṭlaq", f: "das Nūn", v: "3:185", e: "Nūn sākin vor Yāʾ im selben Wort → kein Idġām, deutlich." },
    { s: "وَفِي الْأَرْضِ قِطَعٌ مُتَجَاوِرَاتٌ وَجَنَّاتٌ مِنْ أَعْنَابٍ وَزَرْعٌ وَنَخِيلٌ صِنْوَانٌ", m: "صِنْوَانٌ", r: "Iẓhār muṭlaq", f: "das Nūn", v: "13:4", e: "Nūn sākin vor Wāw im selben Wort → deutlich." },
    /* Mīm sākina */
    { s: "تَرْمِيهِمْ بِحِجَارَةٍ مِنْ سِجِّيلٍ", m: "تَرْمِيهِمْ بِحِجَارَةٍ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "105:4", e: "Mīm sākin vor Bāʾ → Lippen-Iḫfāʾ." },
    { s: "إِنَّ رَبَّهُمْ بِهِمْ يَوْمَئِذٍ لَخَبِيرٌ", m: "رَبَّهُمْ بِهِمْ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "100:11", e: "Mīm sākin vor Bāʾ." },
    { s: "لَكُمْ دِينُكُمْ وَلِيَ دِينِ", m: "لَكُمْ دِينُكُمْ", r: "Iẓhār šafawī", f: "das Mīm", v: "109:6", e: "Mīm sākin vor Dāl → deutlich." },
    { s: "أُولَٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيهَا خَالِدُونَ", m: "هُمْ فِيهَا", r: "Iẓhār šafawī", f: "das Mīm", v: "2:39", e: "Mīm sākin vor Fāʾ → deutlich, hier besonders aufpassen." },
    { s: "الَّذِي أَطْعَمَهُمْ مِنْ جُوعٍ", m: "أَطْعَمَهُمْ مِنْ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "106:4", e: "Mīm sākin vor Mīm → verschmelzen, mit Ġunna." },
    { s: "إِنَّهَا عَلَيْهِمْ مُؤْصَدَةٌ", m: "عَلَيْهِمْ مُؤْصَدَةٌ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "104:8", e: "Mīm sākin vor Mīm." },
    /* Ġunna */
    { s: "ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ", m: "ثُمَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "102:4", e: "Mīm mit Šadda → Ġunna, 2 Ḥarakāt." },
    { s: "عَمَّ يَتَسَاءَلُونَ", m: "عَمَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "78:1", e: "Mīm mit Šadda → Ġunna." },
    { s: "إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", m: "إِنَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "2:20", e: "Nūn mit Šadda → Ġunna." },
    /* Madd */
    { s: "قَالَ رَبِّ اشْرَحْ لِي صَدْرِي", m: "قَالَ", r: "Madd ṭabīʿī", f: "das Alif", v: "20:25", e: "Alif nach Fatḥa, keine Hamza, kein Sukūn danach → 2 Ḥarakāt." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "جَاءَ", r: "Madd muttaṣil", f: "das Alif", v: "110:1", e: "Alif und Hamza im selben Wort → 4–5 Ḥarakāt, Pflicht." },
    { s: "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ", m: "وَالسَّمَاءِ", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "85:1", e: "Alif und Hamza im selben Wort." },
    { s: "أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ", m: "أُولَٰئِكَ", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "2:5", e: "Dehnungsbuchstabe und Hamza im selben Wort." },
    { s: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنْزِلَ إِلَيْكَ", m: "بِمَا أُنْزِلَ", r: "Madd munfaṣil", f: "das Alif von بِمَا", v: "2:4", e: "Alif am Wortende, Hamza am Anfang des nächsten → 4–5, erlaubt." },
    { s: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", m: "إِنَّا أَعْطَيْنَاكَ", r: "Madd munfaṣil", f: "das Alif von إِنَّا", v: "108:1", e: "Getrennt: Madd munfaṣil." },
    { s: "قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا", m: "قُوا أَنْفُسَكُمْ", r: "Madd munfaṣil", f: "das Wāw", v: "66:6", e: "Wāw als Dehnungsbuchstabe am Wortende, Hamza im nächsten Wort." },
    { s: "الْحَاقَّةُ مَا الْحَاقَّةُ", m: "الْحَاقَّةُ", r: "Madd lāzim kalimī", f: "das Alif (erstes Wort)", v: "69:1", e: "Nach dem Alif ein Qāf mit Šadda im selben Wort → 6 Ḥarakāt." },
    { s: "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", m: "الضَّالِّينَ", r: "Madd lāzim kalimī", f: "das Alif nach dem Ḍād", v: "1:7", e: "Nach dem Alif ein Lām mit Šadda → 6 Ḥarakāt." },
    { s: "الم ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ", m: "الم", r: "Madd lāzim ḥarfī", f: "Lām und Mīm", v: "2:1–2", e: "Buchstabennamen am Sūra-Anfang: lāām, mīīm → 6 Ḥarakāt." },
    { s: "ق وَالْقُرْآنِ الْمَجِيدِ", m: "ق", r: "Madd lāzim ḥarfī", f: "der Buchstabenname", v: "50:1", e: "„qāāf“ – drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6." },
    { s: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", m: "نَسْتَعِينُ", r: "Madd ʿāriḍ li-s-sukūn", f: "beim Anhalten am Versende", v: "1:5", e: "Yāʾ als Dehnungsbuchstabe, danach Nūn mit Sukūn durch das Anhalten → 2, 4 oder 6." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "الْعَالَمِينَ", r: "Madd ʿāriḍ li-s-sukūn", f: "das Yāʾ am Ende, beim Anhalten", v: "1:2", e: "Vorübergehendes Sukūn beim Anhalten." },
    { s: "وَآمَنَهُمْ مِنْ خَوْفٍ", m: "خَوْفٍ", r: "Madd al-līn", f: "das Wāw, beim Anhalten", v: "106:4", e: "Wāw sākin nach Fatḥa, beim Anhalten → 2, 4 oder 6." },
    { s: "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ", m: "الْبَيْتِ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten", v: "106:3", e: "Yāʾ sākin nach Fatḥa, beim Anhalten." },
    { s: "لِإِيلَافِ قُرَيْشٍ", m: "قُرَيْشٍ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten", v: "106:1", e: "Līn beim Anhalten." },
    { s: "الَّذِينَ أُوتُوا الْكِتَابَ", m: "أُوتُوا", r: "Madd al-badal", f: "das ū am Anfang", v: "2:101", e: "Hamza vor dem Dehnungsbuchstaben → badal." },
    { s: "لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ", m: "لَهُ", r: "Madd aṣ-ṣila ṣuġrā", f: "das Hāʾ", v: "2:255", e: "Hāʾ des Pronomens zwischen zwei Vokalen, danach keine Hamza → 2." },
    { s: "يَحْسَبُ أَنَّ مَالَهُ أَخْلَدَهُ", m: "مَالَهُ", r: "Madd aṣ-ṣila kubrā", f: "das Hāʾ am Ende", v: "104:3", e: "Danach folgt Hamza → wie munfaṣil, 4–5." },
    { s: "وَكَانَ اللَّهُ غَفُورًا رَحِيمًا", m: "رَحِيمًا", r: "Madd al-ʿiwaḍ", f: "das Ende, beim Anhalten", v: "4:96", e: "Tanwīn mit Fatḥa wird beim Anhalten zu Alif → 2." },
    /* Qalqala */
    { s: "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا", m: "يَدْخُلُونَ", r: "Qalqala ṣuġrā", f: "das Dāl", v: "110:2", e: "Dāl sākin mitten im Wort → kleine Qalqala." },
    { s: "اقْتَرَبَتِ السَّاعَةُ وَانْشَقَّ الْقَمَرُ", m: "اقْتَرَبَتِ", r: "Qalqala ṣuġrā", f: "das Qāf", v: "54:1", e: "Qāf sākin mitten im Wort." },
    { s: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", m: "الْفَلَقِ", r: "Qalqala kubrā", f: "das Qāf beim Anhalten", v: "113:1", e: "Qāf am Wortende, beim Anhalten → große Qalqala." },
    { s: "قُلْ هُوَ اللَّهُ أَحَدٌ", m: "أَحَدٌ", r: "Qalqala kubrā", f: "das Dāl beim Anhalten", v: "112:1", e: "Dāl beim Anhalten → große Qalqala." },
    { s: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ", m: "وَتَبَّ", r: "Qalqala kubrā", f: "das Bāʾ beim Anhalten", v: "111:1", e: "Bāʾ mit Šadda am Versende → beim Anhalten die stärkste Qalqala." },
    /* Lām */
    { s: "وَالشَّمْسِ وَضُحَاهَا", m: "وَالشَّمْسِ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "91:1", e: "Šīn ist ein Sonnenbuchstabe → das Lām wird nicht gesprochen." },
    { s: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", m: "النَّاسِ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "114:1", e: "Nūn ist ein Sonnenbuchstabe." },
    { s: "وَالْقَمَرِ إِذَا تَلَاهَا", m: "وَالْقَمَرِ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "91:2", e: "Qāf ist ein Mondbuchstabe → das Lām wird gesprochen." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "الْحَمْدُ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "1:2", e: "Ḥāʾ ist ein Mondbuchstabe." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "نَصْرُ اللَّهِ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "110:1", e: "Davor Ḍamma → dick." },
    { s: "قَالَ اللَّهُ هَٰذَا يَوْمُ يَنْفَعُ الصَّادِقِينَ صِدْقُهُمْ", m: "قَالَ اللَّهُ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "5:119", e: "Davor Fatḥa → dick." },
    { s: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", m: "اللَّهِ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allah“", v: "1:1", e: "Davor Kasra (bismi) → dünn." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "لِلَّهِ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allah“", v: "1:2", e: "Davor Kasra → dünn." },
    /* Rāʾ */
    { s: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", m: "بِرَبِّ", r: "Rāʾ dick", f: "das Rāʾ", v: "114:1", e: "Rāʾ mit Fatḥa → dick." },
    { s: "وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا", m: "الْقُرْآنَ", r: "Rāʾ dick", f: "das Rāʾ", v: "73:4", e: "Rāʾ sākin nach Ḍamma → dick." },
    { s: "إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا", m: "مِرْصَادًا", r: "Rāʾ dick", f: "das Rāʾ", v: "78:21", e: "Rāʾ sākin nach Kasra, aber danach Ṣād (Isti‘lāʾ) → dick." },
    { s: "ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَرْضِيَّةً", m: "ارْجِعِي", r: "Rāʾ dick", f: "das Rāʾ (beim Beginn)", v: "89:28", e: "Die Kasra davor gehört zur Hamzat al-waṣl → dick." },
    { s: "وَالْعَصْرِ", m: "وَالْعَصْرِ", r: "Rāʾ dick", f: "das Rāʾ beim Anhalten", v: "103:1", e: "Beim Anhalten: davor Ṣād sākin, davor Fatḥa → dick." },
    { s: "رِجَالٌ لَا تُلْهِيهِمْ تِجَارَةٌ وَلَا بَيْعٌ عَنْ ذِكْرِ اللَّهِ", m: "رِجَالٌ", r: "Rāʾ dünn", f: "das Rāʾ", v: "24:37", e: "Rāʾ mit Kasra → dünn." },
    { s: "اذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُ طَغَىٰ", m: "فِرْعَوْنَ", r: "Rāʾ dünn", f: "das Rāʾ", v: "79:17", e: "Rāʾ sākin nach Kasra, danach kein Isti‘lāʾ-Buchstabe → dünn." },
    { s: "إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", m: "قَدِيرٌ", r: "Rāʾ dünn", f: "das Rāʾ beim Anhalten", v: "2:20", e: "Beim Anhalten: davor Yāʾ sākina → dünn." },
    { s: "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", m: "شَرِّ", r: "Rāʾ dünn", f: "das Rāʾ", v: "114:4", e: "Rāʾ mit Kasra → dünn." },
    /* Idġām-Arten und Sakt */
    { s: "فَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنِ اضْرِبْ بِعَصَاكَ الْبَحْرَ", m: "اضْرِبْ بِعَصَاكَ", r: "Idġām miṯlayn", f: "das Bāʾ", v: "26:63", e: "Bāʾ sākin vor Bāʾ → zwei gleiche Buchstaben." },
    { s: "أَيْنَمَا تَكُونُوا يُدْرِكْكُمُ الْمَوْتُ", m: "يُدْرِكْكُمُ", r: "Idġām miṯlayn", f: "das erste Kāf", v: "4:78", e: "Kāf sākin vor Kāf." },
    { s: "وَقَالَتْ طَائِفَةٌ مِنْ أَهْلِ الْكِتَابِ", m: "وَقَالَتْ طَائِفَةٌ", r: "Idġām mutaǧānisayn", f: "das Tāʾ", v: "3:72", e: "Tāʾ vor Ṭāʾ – gleiche Austrittsstelle, andere Eigenschaften." },
    { s: "وَلَوْ أَنَّهُمْ إِذْ ظَلَمُوا أَنْفُسَهُمْ", m: "إِذْ ظَلَمُوا", r: "Idġām mutaǧānisayn", f: "das Ḏāl", v: "4:64", e: "Ḏāl vor Ẓāʾ." },
    { s: "يَا بُنَيَّ ارْكَبْ مَعَنَا", m: "ارْكَبْ مَعَنَا", r: "Idġām mutaǧānisayn", f: "das Bāʾ", v: "11:42", e: "Bāʾ vor Mīm – beide von den Lippen." },
    { s: "وَقُلْ رَبِّ زِدْنِي عِلْمًا", m: "وَقُلْ رَبِّ", r: "Idġām mutaqāribayn", f: "das Lām", v: "20:114", e: "Lām vor Rāʾ → qur-rabbi." },
    { s: "بَلْ رَفَعَهُ اللَّهُ إِلَيْهِ", m: "بَلْ رَفَعَهُ", r: "Idġām mutaqāribayn", f: "das Lām", v: "4:158", e: "Lām vor Rāʾ." },
    { s: "كَلَّا بَلْ رَانَ عَلَىٰ قُلُوبِهِمْ", m: "بَلْ رَانَ", r: "Sakt", f: "zwischen den beiden Wörtern", v: "83:14", e: "Hier ist bei Ḥafṣ ein Sakt – darum kein Idġām von Lām in Rāʾ." },
    { s: "قَالُوا يَا وَيْلَنَا مَنْ بَعَثَنَا مِنْ مَرْقَدِنَا هَٰذَا", m: "مَرْقَدِنَا هَٰذَا", r: "Sakt", f: "zwischen den beiden Wörtern", v: "36:52", e: "Kurz innehalten ohne Atem." },
    { s: "وَقِيلَ مَنْ رَاقٍ", m: "مَنْ رَاقٍ", r: "Sakt", f: "zwischen den beiden Wörtern", v: "75:27", e: "Sakt auf مَنْ – darum kein Idġām ohne Ġunna." }
  ]
};
