/* Taǧwīd-Quiz „Regel erkennen“: eine Stelle aus dem Qurʾān, ein Teil ist markiert – welche Regel gilt dort?
   Jede Aufgabe: { s: Stelle, m: markierte Wörter (genau so wie in s), r: Regel (Name aus RULES),
                   f: worauf man achten soll (optional), v: Sūra:Vers, e: Erklärung }
   Die falschen Antworten nimmt tajwid.js aus der ersten Gruppe (GROUPS), die die Regel enthält – damit man wirklich unterscheiden muss.
   Lesart Ḥafṣ ʿan ʿĀṣim. */
window.TAJWID_REGELN = {
  GROUPS: [
    ["Iẓhār ḥalqī", "Idġām mit Ġunna", "Idġām ohne Ġunna", "Iqlāb", "Iḫfāʾ", "Iẓhār muṭlaq"],
    ["Iḫfāʾ šafawī", "Iẓhār šafawī", "Idġām šafawī (Mīm in Mīm)", "Ġunna (Nūn/Mīm mit Šadda)", "Iqlāb"],
    ["Madd ṭabīʿī", "Madd muttaṣil", "Madd munfaṣil", "Madd lāzim kalimī", "Madd lāzim ḥarfī", "Madd ʿāriḍ li-s-sukūn", "Madd al-līn", "Madd al-badal", "Madd aṣ-ṣila ṣuġrā", "Madd aṣ-ṣila kubrā", "Madd al-ʿiwaḍ"],
    ["Lām šamsiyya", "Lām qamariyya", "Lām in „Allah“ dick", "Lām in „Allah“ dünn", "Lām des Verbs (deutlich)"],
    ["Rāʾ dick", "Rāʾ dünn", "Rāʾ: beides erlaubt", "Lām in „Allah“ dick", "Lām in „Allah“ dünn"],
    ["Idġām miṯlayn", "Idġām mutaǧānisayn", "Idġām mutaqāribayn", "Idġām ohne Ġunna", "Sakt"],
    ["Qalqala ṣuġrā", "Qalqala kubrā", "Lām qamariyya", "Iẓhār ḥalqī", "Iḫfāʾ"]
  ],
  ITEMS: [
    /* Nūn sākina und Tanwīn */
    { s: "إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ", m: "آمَنُوا", r: "Madd al-badal", f: "das ā am Anfang", v: "98:7", e: "Hamza vor dem Dehnungsbuchstaben im selben Wort → badal, 2 Ḥarakāt." },
    { s: "مَنْ آمَنَ بِاللَّهِ وَالْيَوْمِ الْآخِرِ", m: "مَنْ آمَنَ", r: "Iẓhār ḥalqī", f: "das Nūn von مَنْ", v: "2:62", e: "Nūn sākin vor Hamza (Kehllaut) → deutlich." },
    { s: "وَلَهُمْ عَذَابٌ أَلِيمٌ", m: "عَذَابٌ أَلِيمٌ", r: "Iẓhār ḥalqī", f: "das Tanwīn", v: "2:10", e: "Tanwīn vor Hamza → deutlich." },
    { s: "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ", m: "أَنْعَمْتَ", r: "Iẓhār ḥalqī", f: "das Nūn", v: "1:7", e: "Nūn sākin vor ʿAyn → deutlich." },
    { s: "فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", m: "ذَرَّةٍ خَيْرًا", r: "Iẓhār ḥalqī", f: "das Tanwīn", v: "99:7", e: "Tanwīn vor Ḫāʾ (Kehllaut) → deutlich." },
    { s: "فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ", m: "خَيْرًا يَرَهُ", r: "Idġām mit Ġunna", f: "das Tanwīn", v: "99:7", e: "Tanwīn vor Yāʾ (يُومِنُ) über zwei Wörter → Idġām mit Ġunna." },
    { s: "وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ", m: "وَمَنْ يَعْمَلْ", r: "Idġām mit Ġunna", f: "das Nūn", v: "99:8", e: "Nūn sākin vor Yāʾ → may-yaʿmal." },
    { s: "وَخَلَقَ الْجَانَّ مِنْ مَارِجٍ مِنْ نَارٍ", m: "مِنْ نَارٍ", r: "Idġām mit Ġunna", f: "das Nūn von مِنْ", v: "55:15", e: "Nūn sākin vor Nūn → Idġām mit Ġunna." },
    { s: "أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ", m: "مِنْ رَبِّهِمْ", r: "Idġām ohne Ġunna", f: "das Nūn", v: "2:5", e: "Nūn sākin vor Rāʾ → vollständig, ohne Ġunna." },
    { s: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِلْمُتَّقِينَ", m: "هُدًى لِلْمُتَّقِينَ", r: "Idġām ohne Ġunna", f: "das Tanwīn", v: "2:2", e: "Tanwīn vor Lām → ohne Ġunna." },
    { s: "إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ", m: "غَفُورٌ رَحِيمٌ", r: "Idġām ohne Ġunna", f: "das Tanwīn", v: "2:173", e: "Tanwīn vor Rāʾ → ġafūrur-raḥīm." },
    { s: "ثُمَّ عَفَوْنَا عَنْكُمْ مِنْ بَعْدِ ذَٰلِكَ", m: "مِنْ بَعْدِ", r: "Iqlāb", f: "das Nūn", v: "2:52", e: "Nūn sākin vor Bāʾ → Mīm mit Ġunna." },
    { s: "إِنَّ اللَّهَ سَمِيعٌ بَصِيرٌ", m: "سَمِيعٌ بَصِيرٌ", r: "Iqlāb", f: "das Tanwīn", v: "22:75", e: "Tanwīn vor Bāʾ → samīʿum-baṣīr." },
    { s: "كَلَّا لَيُنْبَذَنَّ فِي الْحُطَمَةِ", m: "لَيُنْبَذَنَّ", r: "Iqlāb", f: "das erste Nūn", v: "104:4", e: "Nūn sākin vor Bāʾ im selben Wort → Iqlāb." },
    { s: "وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ", m: "يُنْفِقُونَ", r: "Iḫfāʾ", f: "das Nūn", v: "2:3", e: "Nūn sākin vor Fāʾ → verborgen, mit Ġunna." },
    { s: "الَّذِينَ هُمْ عَنْ صَلَاتِهِمْ سَاهُونَ", m: "عَنْ صَلَاتِهِمْ", r: "Iḫfāʾ", f: "das Nūn", v: "107:5", e: "Nūn sākin vor Ṣād → Iḫfāʾ." },
    { s: "جَنَّاتٍ تَجْرِي مِنْ تَحْتِهَا الْأَنْهَارُ", m: "جَنَّاتٍ تَجْرِي", r: "Iḫfāʾ", f: "das Tanwīn", v: "2:25", e: "Tanwīn vor Tāʾ → Iḫfāʾ." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "وَالْفَتْحُ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "110:1", e: "Fāʾ ist ein Mondbuchstabe → das Lām wird gesprochen." },
    { s: "وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ", m: "الدُّنْيَا", r: "Iẓhār muṭlaq", f: "das Nūn", v: "3:185", e: "Nūn sākin vor Yāʾ im selben Wort → kein Idġām, deutlich." },
    { s: "وَفِي الْأَرْضِ قِطَعٌ مُتَجَاوِرَاتٌ وَجَنَّاتٌ مِنْ أَعْنَابٍ وَزَرْعٌ وَنَخِيلٌ صِنْوَانٌ", m: "صِنْوَانٌ", r: "Iẓhār muṭlaq", f: "das Nūn", v: "13:4", e: "Nūn sākin vor Wāw im selben Wort → deutlich." },
    /* Mīm sākina */
    { s: "تَرْمِيهِمْ بِحِجَارَةٍ مِنْ سِجِّيلٍ", m: "تَرْمِيهِمْ بِحِجَارَةٍ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "105:4", e: "Mīm sākin vor Bāʾ → Lippen-Iḫfāʾ." },
    { s: "إِنَّ رَبَّهُمْ بِهِمْ يَوْمَئِذٍ لَخَبِيرٌ", m: "رَبَّهُمْ بِهِمْ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "100:11", e: "Mīm sākin vor Bāʾ." },
    { s: "لَكُمْ دِينُكُمْ وَلِيَ دِينِ", m: "لَكُمْ دِينُكُمْ", r: "Iẓhār šafawī", f: "das Mīm", v: "109:6", e: "Mīm sākin vor Dāl → deutlich." },
    { s: "أُولَٰئِكَ أَصْحَابُ النَّارِ هُمْ فِيهَا خَالِدُونَ", m: "هُمْ فِيهَا", r: "Iẓhār šafawī", f: "das Mīm", v: "2:39", e: "Mīm sākin vor Fāʾ → deutlich, hier besonders aufpassen." },
    { s: "الَّذِي أَطْعَمَهُمْ مِنْ جُوعٍ", m: "أَطْعَمَهُمْ مِنْ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "106:4", e: "Mīm sākin vor Mīm → verschmelzen, mit Ġunna." },
    { s: "إِنَّهَا عَلَيْهِمْ مُؤْصَدَةٌ", m: "عَلَيْهِمْ مُؤْصَدَةٌ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "104:8", e: "Mīm sākin vor Mīm." },
    /* Ġunna */
    { s: "ثُمَّ كَلَّا سَوْفَ تَعْلَمُونَ", m: "ثُمَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "102:4", e: "Mīm mit Šadda → Ġunna, 2 Ḥarakāt." },
    { s: "عَمَّ يَتَسَاءَلُونَ", m: "عَمَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "78:1", e: "Mīm mit Šadda → Ġunna." },
    { s: "إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", m: "إِنَّ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "2:20", e: "Nūn mit Šadda → Ġunna." },
    /* Madd */
    { s: "قَالَ رَبِّ اشْرَحْ لِي صَدْرِي", m: "قَالَ", r: "Madd ṭabīʿī", f: "das Alif", v: "20:25", e: "Alif nach Fatḥa, keine Hamza, kein Sukūn danach → 2 Ḥarakāt." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "جَاءَ", r: "Madd muttaṣil", f: "das Alif", v: "110:1", e: "Alif und Hamza im selben Wort → 4–5 Ḥarakāt, Pflicht." },
    { s: "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ", m: "وَالسَّمَاءِ", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "85:1", e: "Alif und Hamza im selben Wort." },
    { s: "أُولَٰئِكَ عَلَىٰ هُدًى مِنْ رَبِّهِمْ", m: "أُولَٰئِكَ", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "2:5", e: "Dehnungsbuchstabe und Hamza im selben Wort." },
    { s: "وَالَّذِينَ يُؤْمِنُونَ بِمَا أُنْزِلَ إِلَيْكَ", m: "بِمَا أُنْزِلَ", r: "Madd munfaṣil", f: "das Alif von بِمَا", v: "2:4", e: "Alif am Wortende, Hamza am Anfang des nächsten → 4–5, erlaubt." },
    { s: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", m: "إِنَّا أَعْطَيْنَاكَ", r: "Madd munfaṣil", f: "das Alif von إِنَّا", v: "108:1", e: "Getrennt: Madd munfaṣil." },
    { s: "قُوا أَنْفُسَكُمْ وَأَهْلِيكُمْ نَارًا", m: "قُوا أَنْفُسَكُمْ", r: "Madd munfaṣil", f: "das Wāw", v: "66:6", e: "Wāw als Dehnungsbuchstabe am Wortende, Hamza im nächsten Wort." },
    { s: "الْحَاقَّةُ مَا الْحَاقَّةُ", m: "الْحَاقَّةُ", r: "Madd lāzim kalimī", f: "das Alif (erstes Wort)", v: "69:1", e: "Nach dem Alif ein Qāf mit Šadda im selben Wort → 6 Ḥarakāt." },
    { s: "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", m: "الضَّالِّينَ", r: "Madd lāzim kalimī", f: "das Alif nach dem Ḍād", v: "1:7", e: "Nach dem Alif ein Lām mit Šadda → 6 Ḥarakāt." },
    { s: "الم ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ", m: "الم", r: "Madd lāzim ḥarfī", f: "Lām und Mīm", v: "2:1–2", e: "Buchstabennamen am Sūra-Anfang: lāām, mīīm → 6 Ḥarakāt." },
    { s: "ق وَالْقُرْآنِ الْمَجِيدِ", m: "ق", r: "Madd lāzim ḥarfī", f: "der Buchstabenname", v: "50:1", e: "„qāāf“ – drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6." },
    { s: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", m: "نَسْتَعِينُ", r: "Madd ʿāriḍ li-s-sukūn", f: "beim Anhalten am Versende", v: "1:5", e: "Yāʾ als Dehnungsbuchstabe, danach Nūn mit Sukūn durch das Anhalten → 2, 4 oder 6." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "الْعَالَمِينَ", r: "Madd ʿāriḍ li-s-sukūn", f: "das Yāʾ am Ende, beim Anhalten", v: "1:2", e: "Vorübergehendes Sukūn beim Anhalten." },
    { s: "وَآمَنَهُمْ مِنْ خَوْفٍ", m: "خَوْفٍ", r: "Madd al-līn", f: "das Wāw, beim Anhalten", v: "106:4", e: "Wāw sākin nach Fatḥa, beim Anhalten → 2, 4 oder 6." },
    { s: "فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ", m: "الْبَيْتِ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten", v: "106:3", e: "Yāʾ sākin nach Fatḥa, beim Anhalten." },
    { s: "لِإِيلَافِ قُرَيْشٍ", m: "قُرَيْشٍ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten", v: "106:1", e: "Līn beim Anhalten." },
    { s: "الَّذِينَ أُوتُوا الْكِتَابَ", m: "أُوتُوا", r: "Madd al-badal", f: "das ū am Anfang", v: "2:101", e: "Hamza vor dem Dehnungsbuchstaben → badal." },
    { s: "لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ", m: "لَهُ", r: "Madd aṣ-ṣila ṣuġrā", f: "das Hāʾ", v: "2:255", e: "Hāʾ des Pronomens zwischen zwei Vokalen, danach keine Hamza → 2." },
    { s: "يَحْسَبُ أَنَّ مَالَهُ أَخْلَدَهُ", m: "مَالَهُ", r: "Madd aṣ-ṣila kubrā", f: "das Hāʾ am Ende", v: "104:3", e: "Danach folgt Hamza → wie munfaṣil, 4–5." },
    { s: "وَكَانَ اللَّهُ غَفُورًا رَحِيمًا", m: "رَحِيمًا", r: "Madd al-ʿiwaḍ", f: "das Ende, beim Anhalten", v: "4:96", e: "Tanwīn mit Fatḥa wird beim Anhalten zu Alif → 2." },
    /* Qalqala */
    { s: "وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا", m: "يَدْخُلُونَ", r: "Qalqala ṣuġrā", f: "das Dāl", v: "110:2", e: "Dāl sākin mitten im Wort → kleine Qalqala." },
    { s: "اقْتَرَبَتِ السَّاعَةُ وَانْشَقَّ الْقَمَرُ", m: "اقْتَرَبَتِ", r: "Qalqala ṣuġrā", f: "das Qāf", v: "54:1", e: "Qāf sākin mitten im Wort." },
    { s: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ", m: "الْفَلَقِ", r: "Qalqala kubrā", f: "das Qāf beim Anhalten", v: "113:1", e: "Qāf am Wortende, beim Anhalten → große Qalqala." },
    { s: "قُلْ هُوَ اللَّهُ أَحَدٌ", m: "أَحَدٌ", r: "Qalqala kubrā", f: "das Dāl beim Anhalten", v: "112:1", e: "Dāl beim Anhalten → große Qalqala." },
    { s: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ", m: "وَتَبَّ", r: "Qalqala kubrā", f: "das Bāʾ beim Anhalten", v: "111:1", e: "Bāʾ mit Šadda am Versende → beim Anhalten die stärkste Qalqala." },
    /* Lām */
    { s: "وَالشَّمْسِ وَضُحَاهَا", m: "وَالشَّمْسِ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "91:1", e: "Šīn ist ein Sonnenbuchstabe → das Lām wird nicht gesprochen." },
    { s: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", m: "النَّاسِ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "114:1", e: "Nūn ist ein Sonnenbuchstabe." },
    { s: "وَالْقَمَرِ إِذَا تَلَاهَا", m: "وَالْقَمَرِ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "91:2", e: "Qāf ist ein Mondbuchstabe → das Lām wird gesprochen." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "الْحَمْدُ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "1:2", e: "Ḥāʾ ist ein Mondbuchstabe." },
    { s: "إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ", m: "نَصْرُ اللَّهِ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "110:1", e: "Davor Ḍamma → dick." },
    { s: "قَالَ اللَّهُ هَٰذَا يَوْمُ يَنْفَعُ الصَّادِقِينَ صِدْقُهُمْ", m: "قَالَ اللَّهُ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "5:119", e: "Davor Fatḥa → dick." },
    { s: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ", m: "اللَّهِ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allah“", v: "1:1", e: "Davor Kasra (bismi) → dünn." },
    { s: "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ", m: "لِلَّهِ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allah“", v: "1:2", e: "Davor Kasra → dünn." },
    /* Rāʾ */
    { s: "قُلْ أَعُوذُ بِرَبِّ النَّاسِ", m: "بِرَبِّ", r: "Rāʾ dick", f: "das Rāʾ", v: "114:1", e: "Rāʾ mit Fatḥa → dick." },
    { s: "وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا", m: "الْقُرْآنَ", r: "Rāʾ dick", f: "das Rāʾ", v: "73:4", e: "Rāʾ sākin nach Ḍamma → dick." },
    { s: "إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا", m: "مِرْصَادًا", r: "Rāʾ dick", f: "das Rāʾ", v: "78:21", e: "Rāʾ sākin nach Kasra, aber danach Ṣād (Isti‘lāʾ) → dick." },
    { s: "ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَرْضِيَّةً", m: "ارْجِعِي", r: "Rāʾ dick", f: "das Rāʾ (beim Beginn)", v: "89:28", e: "Die Kasra davor gehört zur Hamzat al-waṣl → dick." },
    { s: "وَالْعَصْرِ", m: "وَالْعَصْرِ", r: "Rāʾ dick", f: "das Rāʾ beim Anhalten", v: "103:1", e: "Beim Anhalten: davor Ṣād sākin, davor Fatḥa → dick." },
    { s: "رِجَالٌ لَا تُلْهِيهِمْ تِجَارَةٌ وَلَا بَيْعٌ عَنْ ذِكْرِ اللَّهِ", m: "رِجَالٌ", r: "Rāʾ dünn", f: "das Rāʾ", v: "24:37", e: "Rāʾ mit Kasra → dünn." },
    { s: "اذْهَبْ إِلَىٰ فِرْعَوْنَ إِنَّهُ طَغَىٰ", m: "فِرْعَوْنَ", r: "Rāʾ dünn", f: "das Rāʾ", v: "79:17", e: "Rāʾ sākin nach Kasra, danach kein Isti‘lāʾ-Buchstabe → dünn." },
    { s: "إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ", m: "قَدِيرٌ", r: "Rāʾ dünn", f: "das Rāʾ beim Anhalten", v: "2:20", e: "Beim Anhalten: davor Yāʾ sākina → dünn." },
    { s: "مِنْ شَرِّ الْوَسْوَاسِ الْخَنَّاسِ", m: "شَرِّ", r: "Rāʾ dünn", f: "das Rāʾ", v: "114:4", e: "Rāʾ mit Kasra → dünn." },
    /* Idġām-Arten und Sakt */
    { s: "فَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنِ اضْرِبْ بِعَصَاكَ الْبَحْرَ", m: "اضْرِبْ بِعَصَاكَ", r: "Idġām miṯlayn", f: "das Bāʾ", v: "26:63", e: "Bāʾ sākin vor Bāʾ → zwei gleiche Buchstaben." },
    { s: "أَيْنَمَا تَكُونُوا يُدْرِكْكُمُ الْمَوْتُ", m: "يُدْرِكْكُمُ", r: "Idġām miṯlayn", f: "das erste Kāf", v: "4:78", e: "Kāf sākin vor Kāf." },
    { s: "وَقَالَتْ طَائِفَةٌ مِنْ أَهْلِ الْكِتَابِ", m: "وَقَالَتْ طَائِفَةٌ", r: "Idġām mutaǧānisayn", f: "das Tāʾ", v: "3:72", e: "Tāʾ vor Ṭāʾ – gleiche Austrittsstelle, andere Eigenschaften." },
    { s: "وَلَوْ أَنَّهُمْ إِذْ ظَلَمُوا أَنْفُسَهُمْ", m: "إِذْ ظَلَمُوا", r: "Idġām mutaǧānisayn", f: "das Ḏāl", v: "4:64", e: "Ḏāl vor Ẓāʾ." },
    { s: "يَا بُنَيَّ ارْكَبْ مَعَنَا", m: "ارْكَبْ مَعَنَا", r: "Idġām mutaǧānisayn", f: "das Bāʾ", v: "11:42", e: "Bāʾ vor Mīm – beide von den Lippen." },
    { s: "وَقُلْ رَبِّ زِدْنِي عِلْمًا", m: "وَقُلْ رَبِّ", r: "Idġām mutaqāribayn", f: "das Lām", v: "20:114", e: "Lām vor Rāʾ → qur-rabbi." },
    { s: "بَلْ رَفَعَهُ اللَّهُ إِلَيْهِ", m: "بَلْ رَفَعَهُ", r: "Idġām mutaqāribayn", f: "das Lām", v: "4:158", e: "Lām vor Rāʾ." },
    { s: "كَلَّا بَلْ رَانَ عَلَىٰ قُلُوبِهِمْ", m: "بَلْ رَانَ", r: "Sakt", f: "zwischen den beiden Wörtern", v: "83:14", e: "Hier ist bei Ḥafṣ ein Sakt – darum kein Idġām von Lām in Rāʾ." },
    { s: "قَالُوا يَا وَيْلَنَا مَنْ بَعَثَنَا مِنْ مَرْقَدِنَا هَٰذَا", m: "مَرْقَدِنَا هَٰذَا", r: "Sakt", f: "zwischen den beiden Wörtern", v: "36:52", e: "Kurz innehalten ohne Atem." },
    { s: "وَقِيلَ مَنْ رَاقٍ", m: "مَنْ رَاقٍ", r: "Sakt", f: "zwischen den beiden Wörtern", v: "75:27", e: "Sakt auf مَنْ – darum kein Idġām ohne Ġunna." },
    /* ---- mehr Stellen, auch schwerere ---- */
    /* Qalqala */
    { s: "إِنَّا أَنْزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ", m: "الْقَدْرِ", r: "Qalqala ṣuġrā", f: "das Dāl", v: "97:1", e: "Dāl sākin mitten im Wort → kleine Qalqala." },
    { s: "وَالْفَجْرِ وَلَيَالٍ عَشْرٍ", m: "وَالْفَجْرِ", r: "Qalqala ṣuġrā", f: "das Ǧīm", v: "89:1–2", e: "Ǧīm sākin mitten im Wort." },
    { s: "وَقَدْ خَلَقَكُمْ أَطْوَارًا", m: "أَطْوَارًا", r: "Qalqala ṣuġrā", f: "das Ṭāʾ", v: "71:14", e: "Ṭāʾ sākin mitten im Wort." },
    { s: "وَيَقْطَعُونَ مَا أَمَرَ اللَّهُ بِهِ أَنْ يُوصَلَ", m: "وَيَقْطَعُونَ", r: "Qalqala ṣuġrā", f: "das Qāf", v: "2:27", e: "Qāf sākin mitten im Wort." },
    { s: "فِي جِيدِهَا حَبْلٌ مِنْ مَسَدٍ", m: "حَبْلٌ", r: "Qalqala ṣuġrā", f: "das Bāʾ", v: "111:5", e: "Bāʾ sākin mitten im Wort." },
    { s: "فِي جِيدِهَا حَبْلٌ مِنْ مَسَدٍ", m: "مَسَدٍ", r: "Qalqala kubrā", f: "das Dāl beim Anhalten", v: "111:5", e: "Dāl am Wortende, beim Anhalten → große Qalqala." },
    { s: "لَمْ يَلِدْ وَلَمْ يُولَدْ", m: "يُولَدْ", r: "Qalqala kubrā", f: "das Dāl beim Anhalten am Versende", v: "112:3", e: "Am Versende angehalten → große Qalqala." },
    { s: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ", m: "خَلَقَ", r: "Qalqala kubrā", f: "das Qāf beim Anhalten", v: "96:1", e: "Beim Anhalten bekommt das Qāf Sukūn → große Qalqala." },
    { s: "وَاللَّهُ مِنْ وَرَائِهِمْ مُحِيطٌ", m: "مُحِيطٌ", r: "Qalqala kubrā", f: "das Ṭāʾ beim Anhalten", v: "85:20", e: "Ṭāʾ am Ende beim Anhalten." },
    /* Ġunna */
    { s: "مِنَ الْجِنَّةِ وَالنَّاسِ", m: "الْجِنَّةِ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "114:6", e: "Nūn mit Šadda → Ġunna, 2 Ḥarakāt." },
    { s: "فَأَمَّا مَنْ أَعْطَىٰ وَاتَّقَىٰ", m: "فَأَمَّا", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "92:5", e: "Mīm mit Šadda → Ġunna." },
    { s: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ", m: "إِنَّا", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn (nicht das Alif)", v: "108:1", e: "Das Nūn hat Šadda → Ġunna. (Das Alif danach wäre Madd munfaṣil.)" },
    { s: "وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ", m: "وَمِمَّا", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "2:3", e: "مِمَّا = مِنْ + مَا: das Nūn ist ins Mīm übergegangen → Mīm mit Šadda, Ġunna." },
    { s: "أَمْ حَسِبْتُمْ أَنْ تَدْخُلُوا الْجَنَّةَ وَلَمَّا يَأْتِكُمْ", m: "الْجَنَّةَ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "2:214", e: "Nūn mit Šadda → Ġunna." },
    { s: "أَمْ حَسِبْتُمْ أَنْ تَدْخُلُوا الْجَنَّةَ وَلَمَّا يَأْتِكُمْ", m: "وَلَمَّا", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Mīm", v: "2:214", e: "Mīm mit Šadda → Ġunna." },
    { s: "إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا", m: "جَهَنَّمَ", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "78:21", e: "Nūn mit Šadda → Ġunna." },
    /* Mīm sākina */
    { s: "أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ", m: "أَلَمْ تَرَ", r: "Iẓhār šafawī", f: "das Mīm", v: "105:1", e: "Mīm sākin vor Tāʾ → deutlich." },
    { s: "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ", m: "عَلَيْهِمْ وَلَا", r: "Iẓhār šafawī", f: "das Mīm", v: "1:7", e: "Mīm sākin vor Wāw → deutlich, hier besonders aufpassen." },
    { s: "لَهُمْ فِيهَا أَزْوَاجٌ مُطَهَّرَةٌ", m: "لَهُمْ فِيهَا", r: "Iẓhār šafawī", f: "das Mīm", v: "4:57", e: "Mīm sākin vor Fāʾ → deutlich, nicht verbergen." },
    { s: "فَاسْتَفْتِهِمْ أَهُمْ أَشَدُّ خَلْقًا أَمْ مَنْ خَلَقْنَا", m: "أَمْ مَنْ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "37:11", e: "Mīm sākin vor Mīm → verschmelzen mit Ġunna." },
    { s: "كَمْ مِنْ فِئَةٍ قَلِيلَةٍ غَلَبَتْ فِئَةً كَثِيرَةً", m: "كَمْ مِنْ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "2:249", e: "Mīm sākin vor Mīm." },
    { s: "وَمَنْ يَعْتَصِمْ بِاللَّهِ فَقَدْ هُدِيَ", m: "يَعْتَصِمْ بِاللَّهِ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "3:101", e: "Mīm sākin vor Bāʾ → Lippen-Iḫfāʾ mit Ġunna." },
    { s: "وَهُمْ بِالْآخِرَةِ كَافِرُونَ", m: "وَهُمْ بِالْآخِرَةِ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "7:45", e: "Mīm sākin vor Bāʾ." },
    /* Lām */
    { s: "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ", m: "قُلِ اللَّهُمَّ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allāhumma“", v: "3:26", e: "Die Kasra auf قُلِ ist nur zur Verbindung (ʿāriḍ) – trotzdem steht vor dem Lām eine Kasra → dünn." },
    { s: "قُلْ هُوَ اللَّهُ أَحَدٌ", m: "اللَّهُ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "112:1", e: "Davor Fatḥa (huwa) → dick." },
    { s: "إِنَّ الَّذِينَ تَوَلَّوْا مِنْكُمْ يَوْمَ الْتَقَى الْجَمْعَانِ", m: "الْتَقَى", r: "Lām des Verbs (deutlich)", f: "das Lām", v: "3:155", e: "Das Lām gehört zum Verb (الْتَقَى) – es wird deutlich gesprochen, auch vor Tāʾ." },
    { s: "أَلْهَاكُمُ التَّكَاثُرُ", m: "أَلْهَاكُمُ", r: "Lām des Verbs (deutlich)", f: "das Lām", v: "102:1", e: "Lām des Verbs → deutlich." },
    { s: "أَلْهَاكُمُ التَّكَاثُرُ", m: "التَّكَاثُرُ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "102:1", e: "Tāʾ ist ein Sonnenbuchstabe → das Lām wird nicht gesprochen." },
    { s: "وَالتِّينِ وَالزَّيْتُونِ", m: "وَالزَّيْتُونِ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "95:1", e: "Zāy ist ein Sonnenbuchstabe." },
    { s: "الْيَوْمَ أَكْمَلْتُ لَكُمْ دِينَكُمْ", m: "الْيَوْمَ", r: "Lām qamariyya", f: "das Lām des Artikels", v: "5:3", e: "Yāʾ ist ein Mondbuchstabe (ابْغِ حَجَّكَ وَخَفْ عَقِيمَهُ) → das Lām wird gesprochen." },
    { s: "الَّذِي جَمَعَ مَالًا وَعَدَّدَهُ", m: "الَّذِي", r: "Lām šamsiyya", f: "das Lām", v: "104:2", e: "Das Lām des Relativpronomens wird assimiliert – wie beim Sonnenbuchstaben." },
    /* Rāʾ */
    { s: "فَانْفَلَقَ فَكَانَ كُلُّ فِرْقٍ كَالطَّوْدِ الْعَظِيمِ", m: "فِرْقٍ", r: "Rāʾ: beides erlaubt", f: "das Rāʾ", v: "26:63", e: "Rāʾ sākin nach Kasra, danach Qāf mit Kasra → dick oder dünn erlaubt." },
    { s: "أَلَيْسَ لِي مُلْكُ مِصْرَ", m: "مِصْرَ", r: "Rāʾ: beides erlaubt", f: "das Rāʾ beim Anhalten", v: "43:51", e: "Beim Anhalten: davor Ṣād sākin (Isti‘lāʾ), davor Kasra → beides erlaubt." },
    { s: "إِرَمَ ذَاتِ الْعِمَادِ", m: "إِرَمَ", r: "Rāʾ dick", f: "das Rāʾ", v: "89:7", e: "Das Rāʾ selbst hat Fatḥa → dick. Die Kasra davor spielt keine Rolle." },
    { s: "أَفِي قُلُوبِهِمْ مَرَضٌ أَمِ ارْتَابُوا", m: "أَمِ ارْتَابُوا", r: "Rāʾ dick", f: "das Rāʾ", v: "24:50", e: "Die Kasra auf أَمِ ist nur zur Verbindung (ʿāriḍ) → das Rāʾ bleibt dick." },
    { s: "وَلَوْ نَزَّلْنَا عَلَيْكَ كِتَابًا فِي قِرْطَاسٍ", m: "قِرْطَاسٍ", r: "Rāʾ dick", f: "das Rāʾ", v: "6:7", e: "Rāʾ sākin nach Kasra, danach Ṭāʾ (Isti‘lāʾ) → dick." },
    { s: "فَلَا تَكُ فِي مِرْيَةٍ مِنْهُ", m: "مِرْيَةٍ", r: "Rāʾ dünn", f: "das Rāʾ", v: "11:17", e: "Rāʾ sākin nach Kasra, danach kein Isti‘lāʾ-Buchstabe → dünn." },
    { s: "لَيْلَةُ الْقَدْرِ خَيْرٌ مِنْ أَلْفِ شَهْرٍ", m: "شَهْرٍ", r: "Rāʾ dick", f: "das Rāʾ beim Anhalten", v: "97:3", e: "Beim Anhalten: davor Hāʾ sākin, davor Fatḥa → dick." },
    { s: "إِنَّا نَحْنُ نَزَّلْنَا الذِّكْرَ", m: "الذِّكْرَ", r: "Rāʾ dick", f: "das Rāʾ beim Weiterlesen", v: "15:9", e: "Beim Weiterlesen hat das Rāʾ Fatḥa → dick (trotz Kasra am Anfang des Wortes)." },
    { s: "وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ", m: "بِالصَّبْرِ", r: "Rāʾ dick", f: "das Rāʾ beim Anhalten", v: "103:3", e: "Beim Anhalten: davor Bāʾ sākin, davor Fatḥa (ṣab) → dick." },
    { s: "إِنَّ هَٰذَا لَسِحْرٌ مُبِينٌ", m: "لَسِحْرٌ", r: "Rāʾ dünn", f: "das Rāʾ, beim Anhalten auf diesem Wort", v: "10:76", e: "Beim Anhalten: davor Ḥāʾ sākin, davor Kasra → dünn." },
    /* Idġām-Arten, Sakt */
    { s: "قَدْ تَبَيَّنَ الرُّشْدُ مِنَ الْغَيِّ", m: "قَدْ تَبَيَّنَ", r: "Idġām mutaǧānisayn", f: "das Dāl", v: "2:256", e: "Dāl vor Tāʾ – gleiche Austrittsstelle." },
    { s: "إِذْ هَمَّتْ طَائِفَتَانِ مِنْكُمْ", m: "هَمَّتْ طَائِفَتَانِ", r: "Idġām mutaǧānisayn", f: "das Tāʾ", v: "3:122", e: "Tāʾ vor Ṭāʾ." },
    { s: "فَلَمَّا أَثْقَلَتْ دَعَوَا اللَّهَ رَبَّهُمَا", m: "أَثْقَلَتْ دَعَوَا", r: "Idġām mutaǧānisayn", f: "das Tāʾ", v: "7:189", e: "Tāʾ vor Dāl." },
    { s: "أَوْ تَتْرُكْهُ يَلْهَثْ ذَٰلِكَ مَثَلُ الْقَوْمِ", m: "يَلْهَثْ ذَٰلِكَ", r: "Idġām mutaǧānisayn", f: "das Ṯāʾ", v: "7:176", e: "Ṯāʾ vor Ḏāl." },
    { s: "أَلَمْ نَخْلُقْكُمْ مِنْ مَاءٍ مَهِينٍ", m: "نَخْلُقْكُمْ", r: "Idġām mutaqāribayn", f: "Qāf und Kāf", v: "77:20", e: "Qāf vor Kāf → naḫlukkum." },
    { s: "قُلْ رَبِّي أَعْلَمُ بِعِدَّتِهِمْ", m: "قُلْ رَبِّي", r: "Idġām mutaqāribayn", f: "das Lām", v: "18:22", e: "Lām vor Rāʾ → qur-rabbī." },
    { s: "وَذَا النُّونِ إِذْ ذَهَبَ مُغَاضِبًا", m: "إِذْ ذَهَبَ", r: "Idġām miṯlayn", f: "das Ḏāl", v: "21:87", e: "Ḏāl sākin vor Ḏāl." },
    { s: "وَقَدْ دَخَلُوا بِالْكُفْرِ", m: "وَقَدْ دَخَلُوا", r: "Idġām miṯlayn", f: "das Dāl", v: "5:61", e: "Dāl sākin vor Dāl." },
    { s: "وَلَمْ يَجْعَلْ لَهُ عِوَجًا قَيِّمًا", m: "عِوَجًا قَيِّمًا", r: "Sakt", f: "zwischen den beiden Wörtern", v: "18:1–2", e: "Bei Ḥafṣ ein Sakt auf عِوَجًا (mit Alif gesprochen) – darum kein Iḫfāʾ des Tanwīn." },
    /* Nūn sākina und Tanwīn, schwerer */
    { s: "وَمَا لَهُمْ مِنْ دُونِهِ مِنْ وَالٍ", m: "مِنْ وَالٍ", r: "Idġām mit Ġunna", f: "das Nūn", v: "13:11", e: "Nūn sākin vor Wāw im nächsten Wort → Idġām mit Ġunna." },
    { s: "وَاللَّهُ عَلِيمٌ حَكِيمٌ", m: "عَلِيمٌ حَكِيمٌ", r: "Iẓhār ḥalqī", f: "das Tanwīn", v: "4:26", e: "Tanwīn vor Ḥāʾ (Kehllaut) → deutlich." },
    { s: "وَنَزَعْنَا مَا فِي صُدُورِهِمْ مِنْ غِلٍّ", m: "مِنْ غِلٍّ", r: "Iẓhār ḥalqī", f: "das Nūn", v: "7:43", e: "Nūn sākin vor Ġayn → deutlich." },
    { s: "وَهُمْ يَنْهَوْنَ عَنْهُ وَيَنْأَوْنَ عَنْهُ", m: "يَنْهَوْنَ", r: "Iẓhār ḥalqī", f: "das erste Nūn", v: "6:26", e: "Nūn sākin vor Hāʾ im selben Wort → deutlich." },
    { s: "قَالَ يَا آدَمُ أَنْبِئْهُمْ بِأَسْمَائِهِمْ", m: "أَنْبِئْهُمْ", r: "Iqlāb", f: "das Nūn", v: "2:33", e: "Nūn sākin vor Bāʾ im selben Wort → Iqlāb." },
    { s: "كُلَّمَا رُزِقُوا مِنْهَا مِنْ ثَمَرَةٍ رِزْقًا", m: "مِنْ ثَمَرَةٍ", r: "Iḫfāʾ", f: "das Nūn", v: "2:25", e: "Nūn sākin vor Ṯāʾ → Iḫfāʾ." },
    { s: "فَأَرْسَلْنَا عَلَيْهِمْ رِيحًا صَرْصَرًا", m: "رِيحًا صَرْصَرًا", r: "Iḫfāʾ", f: "das Tanwīn", v: "41:16", e: "Tanwīn vor Ṣād → Iḫfāʾ." },
    { s: "كَأَنَّهُمْ بُنْيَانٌ مَرْصُوصٌ", m: "بُنْيَانٌ", r: "Iẓhār muṭlaq", f: "das erste Nūn", v: "61:4", e: "Nūn sākin vor Yāʾ im selben Wort → deutlich." },
    { s: "كَأَنَّهُمْ بُنْيَانٌ مَرْصُوصٌ", m: "بُنْيَانٌ مَرْصُوصٌ", r: "Idġām mit Ġunna", f: "das Tanwīn", v: "61:4", e: "Tanwīn vor Mīm im nächsten Wort → Idġām mit Ġunna." },
    /* Madd, schwerer */
    { s: "آلْآنَ وَقَدْ عَصَيْتَ قَبْلُ", m: "آلْآنَ", r: "Madd lāzim kalimī", f: "das erste ā", v: "10:91", e: "Nach dem Alif ein ursprüngliches Sukūn (das Lām) ohne Šadda → kalimī muḫaffaf, 6 Ḥarakāt." },
    { s: "طه مَا أَنْزَلْنَا عَلَيْكَ الْقُرْآنَ لِتَشْقَىٰ", m: "طه", r: "Madd ṭabīʿī", f: "die Buchstabennamen", v: "20:1–2", e: "Ṭā und Hā gehören zu „حَيٌّ طَهُرَ“ – ihre Namen haben zwei Buchstaben → nur 2 Ḥarakāt." },
    { s: "حم عسق", m: "عسق", r: "Madd lāzim ḥarfī", f: "das Sīn", v: "42:1–2", e: "Der Name sīn: drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6 Ḥarakāt." },
    { s: "وَلَا آمِّينَ الْبَيْتَ الْحَرَامَ", m: "آمِّينَ", r: "Madd lāzim kalimī", f: "das erste ā", v: "5:2", e: "Badal (Hamza davor) und lāzim (Mīm mit Šadda danach) – die stärkere Ursache zählt: 6 Ḥarakāt." },
    { s: "وَجِيءَ يَوْمَئِذٍ بِجَهَنَّمَ", m: "وَجِيءَ", r: "Madd muttaṣil", f: "das Yāʾ vor der Hamza", v: "89:23", e: "Yāʾ als Dehnungsbuchstabe und Hamza im selben Wort." },
    { s: "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ", m: "الشِّتَاءِ", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "106:2", e: "Alif und Hamza im selben Wort." },
    { s: "إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ", m: "وَالصَّيْفِ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten", v: "106:2", e: "Yāʾ sākin nach Fatḥa, beim Anhalten → Līn." },
    { s: "وَفِي أَنْفُسِكُمْ أَفَلَا تُبْصِرُونَ", m: "وَفِي أَنْفُسِكُمْ", r: "Madd munfaṣil", f: "das Yāʾ von فِي", v: "51:21", e: "Yāʾ als Dehnungsbuchstabe am Wortende, Hamza im nächsten Wort." },
    { s: "وَلَا يُشْرِكْ بِعِبَادَةِ رَبِّهِ أَحَدًا", m: "رَبِّهِ أَحَدًا", r: "Madd aṣ-ṣila kubrā", f: "das Hāʾ", v: "18:110", e: "Hāʾ des Pronomens zwischen zwei Vokalen, danach Hamza → ṣila kubrā, 4–5." },
    { s: "وَيَخْلُدْ فِيهِ مُهَانًا", m: "فِيهِ", r: "Madd aṣ-ṣila ṣuġrā", f: "das Hāʾ", v: "25:69", e: "Ausnahme: obwohl davor ein Sākin steht, wird das Hāʾ hier gedehnt (2 Ḥarakāt)." },
    /* ---- noch mehr schwere Stellen ---- */
    /* eine Stelle, drei Regeln */
    { s: "وَمِنْهُمْ مَنْ يَقُولُ رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", m: "وَمِنْهُمْ", r: "Iẓhār ḥalqī", f: "das Nūn", v: "2:200", e: "Nūn sākin vor Hāʾ – auch im selben Wort deutlich." },
    { s: "وَمِنْهُمْ مَنْ يَقُولُ رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", m: "وَمِنْهُمْ مَنْ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm von وَمِنْهُمْ", v: "2:200", e: "Mīm sākin vor Mīm → verschmelzen mit Ġunna." },
    { s: "وَمِنْهُمْ مَنْ يَقُولُ رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً", m: "مَنْ يَقُولُ", r: "Idġām mit Ġunna", f: "das Nūn von مَنْ", v: "2:200", e: "Nūn sākin vor Yāʾ im nächsten Wort." },
    /* Nūn und Tanwīn */
    { s: "يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ وَقُولُوا قَوْلًا سَدِيدًا", m: "قَوْلًا سَدِيدًا", r: "Iḫfāʾ", f: "das Tanwīn", v: "33:70", e: "Tanwīn vor Sīn → Iḫfāʾ." },
    { s: "إِنِّي أَحْبَبْتُ حُبَّ الْخَيْرِ عَنْ ذِكْرِ رَبِّي", m: "عَنْ ذِكْرِ", r: "Iḫfāʾ", f: "das Nūn", v: "38:32", e: "Nūn sākin vor Ḏāl → Iḫfāʾ." },
    { s: "لَئِنْ شَكَرْتُمْ لَأَزِيدَنَّكُمْ", m: "لَئِنْ شَكَرْتُمْ", r: "Iḫfāʾ", f: "das Nūn", v: "14:7", e: "Nūn sākin vor Šīn → Iḫfāʾ." },
    { s: "إِنَّ اللَّهَ عَلِيمٌ بِذَاتِ الصُّدُورِ", m: "عَلِيمٌ بِذَاتِ", r: "Iqlāb", f: "das Tanwīn", v: "3:119", e: "Tanwīn vor Bāʾ → Mīm mit Ġunna." },
    { s: "وَمَا بِكُمْ مِنْ نِعْمَةٍ فَمِنَ اللَّهِ", m: "مِنْ نِعْمَةٍ", r: "Idġām mit Ġunna", f: "das Nūn von مِنْ", v: "16:53", e: "Nūn sākin vor Nūn → Idġām mit Ġunna." },
    { s: "لِيُنْذِرَ بَأْسًا شَدِيدًا مِنْ لَدُنْهُ", m: "مِنْ لَدُنْهُ", r: "Idġām ohne Ġunna", f: "das Nūn von مِنْ", v: "18:2", e: "Nūn sākin vor Lām → ohne Ġunna." },
    { s: "وَمِنَ النَّخْلِ مِنْ طَلْعِهَا قِنْوَانٌ دَانِيَةٌ", m: "قِنْوَانٌ", r: "Iẓhār muṭlaq", f: "das erste Nūn", v: "6:99", e: "Nūn sākin vor Wāw im selben Wort → deutlich, kein Idġām." },
    /* Mīm */
    { s: "أَفْتَرَىٰ عَلَى اللَّهِ كَذِبًا أَمْ بِهِ جِنَّةٌ", m: "أَمْ بِهِ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "34:8", e: "Mīm sākin vor Bāʾ → Lippen-Iḫfāʾ." },
    { s: "وَمَا هُمْ بِمُؤْمِنِينَ", m: "هُمْ بِمُؤْمِنِينَ", r: "Iḫfāʾ šafawī", f: "das Mīm", v: "2:8", e: "Mīm sākin vor Bāʾ." },
    { s: "فَقَالُوا إِنَّا إِلَيْكُمْ مُرْسَلُونَ", m: "إِلَيْكُمْ مُرْسَلُونَ", r: "Idġām šafawī (Mīm in Mīm)", f: "das Mīm", v: "36:14", e: "Mīm sākin vor Mīm." },
    /* Ġunna */
    { s: "إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ", m: "إِنَّمَا", r: "Ġunna (Nūn/Mīm mit Šadda)", f: "das Nūn", v: "49:10", e: "Nūn mit Šadda → Ġunna." },
    /* Madd */
    { s: "وَجَاءُوا أَبَاهُمْ عِشَاءً يَبْكُونَ", m: "عِشَاءً", r: "Madd muttaṣil", f: "das Alif vor der Hamza", v: "12:16", e: "Alif und Hamza im selben Wort." },
    { s: "وَجَاءُوا أَبَاهُمْ عِشَاءً يَبْكُونَ", m: "وَجَاءُوا أَبَاهُمْ", r: "Madd munfaṣil", f: "das Wāw am Ende von جَاءُوا", v: "12:16", e: "Das Wāw steht nach einer Hamza (badal) und vor der Hamza des nächsten Wortes (munfaṣil) – die stärkere Ursache zählt: munfaṣil." },
    { s: "وَبِالْآخِرَةِ هُمْ يُوقِنُونَ", m: "وَبِالْآخِرَةِ", r: "Madd al-badal", f: "das ā nach dem Lām", v: "2:4", e: "In الْآخِرَة steht die Hamza vor dem Alif → badal, 2 Ḥarakāt." },
    { s: "شَهْرُ رَمَضَانَ الَّذِي أُنْزِلَ فِيهِ الْقُرْآنُ هُدًى لِلنَّاسِ", m: "الْقُرْآنُ", r: "Madd al-badal", f: "das ā nach der Hamza, beim Weiterlesen", v: "2:185", e: "Hamza vor dem Alif im selben Wort → badal (beim Anhalten wäre es ʿāriḍ)." },
    { s: "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ", m: "وَإِنَّا إِلَيْهِ", r: "Madd munfaṣil", f: "das Alif von وَإِنَّا", v: "2:156", e: "Alif am Wortende, Hamza am Anfang des nächsten." },
    { s: "تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ", m: "يَدَا أَبِي", r: "Madd munfaṣil", f: "das Alif von يَدَا", v: "111:1", e: "Getrennt: Madd munfaṣil." },
    { s: "هَا أَنْتُمْ هَٰؤُلَاءِ حَاجَجْتُمْ", m: "هَا أَنْتُمْ", r: "Madd munfaṣil", f: "das Alif von هَا", v: "3:66", e: "هَا ist ein eigenes Wort → Hamza im nächsten Wort: munfaṣil." },
    { s: "هَا أَنْتُمْ هَٰؤُلَاءِ حَاجَجْتُمْ", m: "هَٰؤُلَاءِ", r: "Madd muttaṣil", f: "das Alif vor der letzten Hamza", v: "3:66", e: "Alif und Hamza im selben Wort." },
    { s: "قُلْ آللَّهُ أَذِنَ لَكُمْ", m: "آللَّهُ", r: "Madd lāzim kalimī", f: "das erste ā", v: "10:59", e: "Madd al-farq: die zweite Hamza wird zu Alif mit Šadda-Lām danach → 6 Ḥarakāt (wie lāzim)." },
    { s: "كهيعص ذِكْرُ رَحْمَتِ رَبِّكَ عَبْدَهُ زَكَرِيَّا", m: "كهيعص", r: "Madd lāzim ḥarfī", f: "das Kāf", v: "19:1–2", e: "kāf: drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6." },
    { s: "كهيعص ذِكْرُ رَحْمَتِ رَبِّكَ عَبْدَهُ زَكَرِيَّا", m: "كهيعص", r: "Madd ṭabīʿī", f: "das Hāʾ", v: "19:1–2", e: "hā gehört zu „حَيٌّ طَهُرَ“ – nur 2 Ḥarakāt." },
    { s: "طس تِلْكَ آيَاتُ الْقُرْآنِ", m: "طس", r: "Madd ṭabīʿī", f: "das Ṭāʾ", v: "27:1", e: "ṭā – zwei Buchstaben → natürliche Dehnung." },
    { s: "طس تِلْكَ آيَاتُ الْقُرْآنِ", m: "طس", r: "Madd lāzim ḥarfī", f: "das Sīn", v: "27:1", e: "sīn – drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6." },
    { s: "حم تَنْزِيلُ الْكِتَابِ مِنَ اللَّهِ الْعَزِيزِ الْعَلِيمِ", m: "حم", r: "Madd ṭabīʿī", f: "das Ḥāʾ", v: "40:1–2", e: "ḥā – nur 2 Ḥarakāt." },
    { s: "ن وَالْقَلَمِ وَمَا يَسْطُرُونَ", m: "ن", r: "Madd lāzim ḥarfī", f: "der Buchstabenname", v: "68:1", e: "nūn – drei Buchstaben, der mittlere ein Dehnungsbuchstabe → 6." },
    { s: "إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا", m: "حَكِيمًا", r: "Madd al-ʿiwaḍ", f: "das Ende, beim Anhalten", v: "4:11", e: "Tanwīn mit Fatḥa → beim Anhalten Alif." },
    { s: "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ", m: "رَيْبَ", r: "Madd al-līn", f: "das Yāʾ, beim Anhalten auf رَيْبَ", v: "2:2", e: "Yāʾ sākin nach Fatḥa; hält man hier an (Muʿānaqa-Stelle), entsteht Līn." },
    { s: "إِنَّهُ كَانَ بِعِبَادِهِ خَبِيرًا بَصِيرًا", m: "بِعِبَادِهِ", r: "Madd aṣ-ṣila ṣuġrā", f: "das Hāʾ am Ende", v: "17:30", e: "Hāʾ des Pronomens zwischen zwei Vokalen, danach keine Hamza." },
    /* Qalqala */
    { s: "وَالسَّمَاءِ ذَاتِ الْبُرُوجِ", m: "الْبُرُوجِ", r: "Qalqala kubrā", f: "das Ǧīm beim Anhalten", v: "85:1", e: "Ǧīm am Wortende beim Anhalten." },
    { s: "وَالطُّورِ وَكِتَابٍ مَسْطُورٍ", m: "مَسْطُورٍ", r: "Qalqala ṣuġrā", f: "das Ṭāʾ", v: "52:1–2", e: "Ṭāʾ sākin mitten im Wort." },
    { s: "إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ", m: "الْأَبْتَرُ", r: "Qalqala ṣuġrā", f: "das Bāʾ", v: "108:3", e: "Bāʾ sākin mitten im Wort." },
    /* Lām */
    { s: "قَالَتْ رُسُلُهُمْ أَفِي اللَّهِ شَكٌّ", m: "أَفِي اللَّهِ", r: "Lām in „Allah“ dünn", f: "das Lām in „Allah“", v: "14:10", e: "Das Yāʾ fällt beim Weiterlesen weg; davor steht die Kasra des Fāʾ → dünn." },
    { s: "وَاتَّقُوا اللَّهَ لَعَلَّكُمْ تُفْلِحُونَ", m: "وَاتَّقُوا اللَّهَ", r: "Lām in „Allah“ dick", f: "das Lām in „Allah“", v: "2:189", e: "Das Wāw fällt beim Weiterlesen weg; davor steht die Ḍamma des Qāf → dick." },
    { s: "الرِّجَالُ قَوَّامُونَ عَلَى النِّسَاءِ", m: "الرِّجَالُ", r: "Lām šamsiyya", f: "das Lām des Artikels", v: "4:34", e: "Rāʾ ist ein Sonnenbuchstabe." },
    { s: "الرِّجَالُ قَوَّامُونَ عَلَى النِّسَاءِ", m: "الرِّجَالُ", r: "Rāʾ dünn", f: "das Rāʾ", v: "4:34", e: "Rāʾ mit Kasra → dünn." },
    /* Rāʾ */
    { s: "مَا يُفَرِّقُونَ بِهِ بَيْنَ الْمَرْءِ وَزَوْجِهِ", m: "الْمَرْءِ", r: "Rāʾ dick", f: "das Rāʾ", v: "2:102", e: "Rāʾ sākin nach Fatḥa → dick." },
    { s: "فَلَوْلَا نَفَرَ مِنْ كُلِّ فِرْقَةٍ مِنْهُمْ طَائِفَةٌ", m: "فِرْقَةٍ", r: "Rāʾ dick", f: "das Rāʾ", v: "9:122", e: "Rāʾ sākin nach Kasra, danach Qāf (Isti‘lāʾ) mit Fatḥa → dick." },
    { s: "إِنَّ رَبَّكَ لَبِالْمِرْصَادِ", m: "لَبِالْمِرْصَادِ", r: "Rāʾ dick", f: "das Rāʾ", v: "89:14", e: "Rāʾ sākin nach Kasra, danach Ṣād → dick." },
    { s: "وَالْفَجْرِ وَلَيَالٍ عَشْرٍ", m: "وَالْفَجْرِ", r: "Rāʾ dick", f: "das Rāʾ beim Anhalten", v: "89:1", e: "Beim Anhalten: davor Ǧīm sākin, davor Fatḥa → dick." },
    { s: "ص وَالْقُرْآنِ ذِي الذِّكْرِ", m: "الذِّكْرِ", r: "Rāʾ dünn", f: "das Rāʾ beim Anhalten", v: "38:1", e: "Beim Anhalten: davor Kāf sākin, davor Kasra → dünn." },
    { s: "إِنَّ رَبَّهُمْ بِهِمْ يَوْمَئِذٍ لَخَبِيرٌ", m: "لَخَبِيرٌ", r: "Rāʾ dünn", f: "das Rāʾ beim Anhalten", v: "100:11", e: "Beim Anhalten: davor Yāʾ sākina → dünn." },
    { s: "وَأَسَلْنَا لَهُ عَيْنَ الْقِطْرِ", m: "الْقِطْرِ", r: "Rāʾ: beides erlaubt", f: "das Rāʾ beim Anhalten", v: "34:12", e: "Davor Ṭāʾ sākin (Isti‘lāʾ), davor Kasra → dick oder dünn erlaubt." },
    /* Idġām-Arten */
    { s: "فَقَالَ أَحَطْتُ بِمَا لَمْ تُحِطْ بِهِ", m: "أَحَطْتُ", r: "Idġām mutaǧānisayn", f: "Ṭāʾ und Tāʾ", v: "27:22", e: "Ṭāʾ vor Tāʾ – unvollständiger Idġām: die Schwere (Iṭbāq) des Ṭāʾ bleibt hörbar." },
    { s: "لَئِنْ بَسَطْتَ إِلَيَّ يَدَكَ لِتَقْتُلَنِي", m: "بَسَطْتَ", r: "Idġām mutaǧānisayn", f: "Ṭāʾ und Tāʾ", v: "5:28", e: "Unvollständiger Idġām des Ṭāʾ ins Tāʾ." },
    { s: "وَمِنْ قَبْلُ مَا فَرَّطْتُمْ فِي يُوسُفَ", m: "فَرَّطْتُمْ", r: "Idġām mutaǧānisayn", f: "Ṭāʾ und Tāʾ", v: "12:80", e: "Ṭāʾ vor Tāʾ, unvollständig." },
    { s: "ذَٰلِكَ بِمَا عَصَوْا وَكَانُوا يَعْتَدُونَ", m: "عَصَوْا وَكَانُوا", r: "Idġām miṯlayn", f: "das Wāw", v: "2:61", e: "Wāw sākin nach Fatḥa (Līn) vor Wāw → Idġām. (Nach Ḍamma, z. B. قَالُوا وَهُمْ, wäre es ein Dehnungsbuchstabe – dann kein Idġām.)" },
    { s: "وَقُلْ لَهُمْ فِي أَنْفُسِهِمْ قَوْلًا بَلِيغًا", m: "وَقُلْ لَهُمْ", r: "Idġām miṯlayn", f: "das Lām", v: "4:63", e: "Lām sākin vor Lām." }
  ]
};
